on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/oai.yml'

name: Harvest DiVA records using OAI-PMH and upload oai.db to S3/minio

jobs:
  docker:
    runs-on: ubuntu-latest
    container: ghcr.io/kth-library/kthcorpus
    timeout-minutes: 20
    env:
      MC_HOST_kthb: ${{ secrets.MC_HOST_KTHB }}
    steps:
    - name: Free Disk Space
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: true
        android: true
        dotnet: true
        haskell: true
        large-packages: false
        swap-storage: true
    - name: Download db, refresh and upload (OAI-PMH Harvest)
      run: |
          R -e 'kthcorpus:::oai_db_refresh()'
          R -e 'kthcorpus:::diva_upload_s3(kthcorpus:::oai_db_path())'
    